winebus.sys: Use uint16_t instead of __u16.
This addresses a regression introduced by commit e603bbf69c7 where we'd get
  dlls/winebus.sys/bus_udev.c: In function ‘lnxev_device_haptics_thread’:
  dlls/winebus.sys/bus_udev.c:711:36: error: ‘__u16’ undeclared
on FreeBSD 13.

(cherry picked from commit 765fff593c58569c56d924db89876febc9a0208b)